# Generated by Django 3.1 on 2020-09-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('address', models.CharField(max_length=100)),
                ('atm', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('registered_dttm', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
